spring:
  application:
    name: Meshpay

  datasource:
    url: jdbc:postgresql://localhost:5432/Meshpay
    username: postgres
    password: newpassword

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: "AIzaSyBculunRgxDcaivvGvsNAkqi4fFVFwUis4"
logging:
  level:
    com:
      radhika:
        meshpay: INFO

  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

upi:
  mesh:
    idempotency-ttl-seconds: 86400
    packet-max-age-seconds: 86400